# Generated by Django 5.1.6 on 2025-04-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_resume_city_alter_resume_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='img_url',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
